name: Run benchmarks
permissions:
  contents: read
 
on:
  push:
    branches: 
    - "*"
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  benchmark:
    runs-on:
      group: ARM LINUX SHARED
      labels: arm-8core-linux
    strategy:
      matrix:
        go-version: [ '1.24' ]

    steps:
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b
        with:
          go-version: ${{ matrix.go-version }}
      - name: Display Go version
        run: go version
      - name: Restore main benchmark
        uses: actions/cache/restore@v4
        id: restore-main-benchmark
        with:
          path: bench/main.txt
          key: main-benchmark-6
      - name: Checkout main
        if: steps.restore-main-benchmark.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          ref: main
          clean: false
      - name: Install dependencies
        if: steps.restore-main-benchmark.outputs.cache-hit != 'true'
        run: go get .
      - name: Build
        if: steps.restore-main-benchmark.outputs.cache-hit != 'true'
        run: go build -v ./...
      - run: mkdir -p bench
        if: steps.restore-main-benchmark.outputs.cache-hit != 'true'
      - name: Benchmark
        if: steps.restore-main-benchmark.outputs.cache-hit != 'true'
        run: go test -timeout=9999999s -bench=. -benchmem -count=6  ./... | tee bench/main.txt
      - name: Save main benchmark
        uses: actions/cache/save@v4
        if: steps.restore-main-benchmark.outputs.cache-hit != 'true'
        with:
          path: bench/main.txt
          key: ${{ steps.restore-main-benchmark.outputs.cache-primary-key }}
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Restore main benchmark
        uses: actions/cache/restore@v4
        with:
          path: bench/main.txt
          key: main-benchmark-6
          fail-on-cache-miss: true
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Benchmark
        run: go test -timeout=9999999s -bench=. -benchmem -count=6  ./... | tee bench/${{github.sha}}.txt
      - name: Install benchstat
        run: go get -u golang.org/x/perf/cmd/benchstat && go install golang.org/x/perf/cmd/benchstat
      - name: Compare benchmarks
        run: benchstat bench/main.txt bench/${{github.sha}}.txt | tee bench/benchstat.txt
      - name: Store benchmark
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-${{ github.sha }}
          path: bench


  benchmark_main:
    if: github.ref == 'refs/heads/main'
    runs-on:
      group: ARM LINUX SHARED
      labels: arm-8core-linux
    strategy:
      matrix:
        go-version: [ '1.24' ]
    steps:
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b
        with:
          go-version: ${{ matrix.go-version }}
      - name: Display Go version
        run: go version
      - name: Checkout main
        uses: actions/checkout@v4
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - run: mkdir -p bench
      - name: Cache main benchmark
        uses: actions/cache@v4
        with:
          path: bench/main.txt
          key: main-benchmark-6
      - name: Benchmark
        run: go test -timeout=9999999s -bench=. -benchmem -count=6  ./... | tee bench/main.txt    
